#!/bin/sh
xrandr --output VIRTUAL1 --off --output DP2 --off --output DP1 --off --output HDMI2 --off --output HDMI1 --off --output LVDS1 --mode 1600x900 --pos 0x1050 --rotate normal --output VGA1 --primary --mode 1680x1050 --pos 0x0 --rotate normal
