#!/bin/sh
updates_aur=$(yay -Qum | wc -l)
updates_arch=$(checkupdates | wc -l)
packages_to_update=$(("$updates_arch" + "$updates_aur"))

if [ "$packages_to_update" = 0 ]; then
  echo ""
else
  echo  $(yay -Qum | wc -l)
fi
